#CICD WORKFLOW

name: Deploy ECR

# quando minha ação vai acontecer? 
# Trigger

on: #quando
  push: #novo código
    branches: [ main ] #nesta branch -> start action

jobs:

  build:
    
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key-id: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
        
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build, tag, push.
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: cicd
        IMAGE_TAG: cicd
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./aula_4/Dockerfile
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
